In [3]:
import numpy as np
import time
import sys

In [4]:
# in python
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [5]:
#In Numpy
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [6]:
L1=range(size)
L2=range(size)
A1=np.arange(size)

NameError: name 'size' is not defined

In [7]:
a=np.array([[1,2],
           [3,4],
           [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
a.ndim

2

In [10]:
a.shape

(3, 2)

In [11]:
a.itemsize

4

In [12]:
a=np.array([[1,2],
           [3,4],
           [5,6]],dtype=np.complex)#represented in the  form o complex.
a

C:\Users\91790\AppData\Local\Temp\ipykernel_12080\2949460448.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  [5,6]],dtype=np.complex)#represented in the  form o complex.


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [13]:
z=np.zeros((2,2))
z


array([[0., 0.],
       [0., 0.]])

In [14]:
o=np.ones((4,6))
o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
l=range(2)
l

range(0, 2)

In [16]:
r=np.arange(4)
r

array([0, 1, 2, 3])

In [17]:
print("Concatenation example:")
print(np.char.add(['hello','hi'],['abc','xyz']))

Concatenation example:
['helloabc' 'hixyz']


In [18]:
print(np.char.multiply('Hello kundu ',5,fillchar='-'))


TypeError: _multiply_dispatcher() got an unexpected keyword argument 'fillchar'

In [19]:
ex=np.char.center("hello Kundu love",1133)
print(ex)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               hello Kundu love                                                                                                                                                                                                                                                                                                                                                                                                                                         

In [26]:
arr1=np.array([1,3,4,6])
print(arr1)


[1 3 4 6]


In [34]:
arr1=np.empty(4)

In [35]:
print(arr1)

[0. 0. 0. 0.]


In [36]:
arr1

array([0., 0., 0., 0.])

In [38]:
arr2=np.arange(9)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr2=np.eye(3,8)

In [42]:
arr2

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [56]:
arr=np.linspace(1,10,10)

In [55]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [71]:
arr=np.linspace(0,1,1)

In [72]:
arr

array([0.])

In [82]:
arr=np.random.rand(1,5)
arr

array([[[0.4407032 , 0.99596622, 0.90709247, 0.5729438 , 0.7614635 ],
        [0.97903853, 0.13234801, 0.5885412 , 0.99880478, 0.51140205],
        [0.24155583, 0.45981348, 0.77133648, 0.51630604, 0.53378263],
        [0.2696209 , 0.08284006, 0.53089526, 0.34528264, 0.44128167],
        [0.32125831, 0.37277095, 0.90323217, 0.1873233 , 0.42392386]]])

In [87]:
arr=np.random.randn(6,5)
arr

array([[-0.68526163,  1.16605282, -1.32736311, -1.24198664, -0.66776725],
       [ 0.55109137,  0.21366757,  1.24471109, -0.33399665, -0.08274083],
       [-0.56008996, -0.30353194, -0.60119061,  1.50476271,  0.78451972],
       [ 1.02774488, -1.78843953,  0.08352168,  1.02628343,  0.13736933],
       [ 0.98982995, -1.18611778,  0.03108674,  1.4000605 , -0.29270681],
       [-2.01551398,  0.86209967, -0.10570333, -0.32838188,  1.16011536]])

In [96]:
arr=np.random.ranf()
arr

0.5792242057711037

In [103]:
arr=np.random.randint(4)
arr

3

In [109]:

var=np.array([1,4,5,6,3])
print(var.dtype)

int32


In [110]:
var=np.array([1,4,5,6,3],dtype=np.int8)
print(var.dtype)

int8


In [111]:
var=np.array([1,4,5,6,3],dtype="f")
print(var.dtype)

float32


In [118]:
arr2=np.array([[1,2,3],[3,5,6]])
print(arr2)
for i in np.nditer(arr2):
    print(i)

[[1 2 3]
 [3 5 6]]
1
2
3
3
5
6


In [125]:
arr2=np.array([[1,2,3],
               [3,5,6],
               [54,6,7],
               [5,67,87]])
print(arr2)
for i in np.nditer(arr2):
    print(i)


[[ 1  2  3]
 [ 3  5  6]
 [54  6  7]
 [ 5 67 87]]
1
2
3
3
5
6
54
6
7
5
67
87


In [127]:
arr2=np.array([[1,2,3],
               [3,5,6],
               [54,6,7],
               [5,67,87]])
print(arr2)
for i,d in np.ndenumerate(arr2):
    print("indexes:",i,"values:",d)


[[ 1  2  3]
 [ 3  5  6]
 [54  6  7]
 [ 5 67 87]]
indexes: (0, 0) values: 1
indexes: (0, 1) values: 2
indexes: (0, 2) values: 3
indexes: (1, 0) values: 3
indexes: (1, 1) values: 5
indexes: (1, 2) values: 6
indexes: (2, 0) values: 54
indexes: (2, 1) values: 6
indexes: (2, 2) values: 7
indexes: (3, 0) values: 5
indexes: (3, 1) values: 67
indexes: (3, 2) values: 87


In [129]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
join=np.concatenate((arr1,arr2))
print(join)

[1 2 3 4 4 5 6 7]


In [136]:
arr1=np.array([1,2,3,4,2,4,5,6,7,3,2,35,34,6,74])
split=np.array_split(arr1,7)
print(split)

[array([1, 2, 3]), array([4, 2]), array([4, 5]), array([6, 7]), array([3, 2]), array([35, 34]), array([ 6, 74])]
